routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TVController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [TVController::class, 'index'])->name('index');
Route::get('/genre/{name}', [TVController::class, 'sort'])->name('sort');

Route::get('/find', function () {
    return view('guest.find');
})->name('find');

Route::post('/find/submit', [TVController::class, 'find'])->name('find-form');

Auth::routes([
    'reset' => false,
    'confirm' => false,
    'verify' => false,
    'register' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('admin/program', 'App\Http\Controllers\AdminController', ['parameters' => [
        'program' => 'id'
    ]]);
});

app/Models/Genre_list.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class genre_list extends Model
{
    use HasFactory;

    protected $table = 'genre_list';
    public $timestamps = false;

    public function genres()
    {
        return DB::table('genre_list')->get();
    }
}

app/Models/TvName.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class TVname extends Model
{
    use HasFactory;

    protected $table = "tvName";
    public $timestamps = false;

    public function query_name()
    {
        return DB::table('tvName', 't')
            ->join('genre_list as gl', 'gl.genre_id', '=', 't.genre_id')
            ->select('t.*', 'gl.*');
    }
    public function data()
    {
        return $this->query_name()
            ->orderBy('t.time')
            ->get();
    }
    public function oneData($name)
    {
        return $this->query_name()
            ->where('t.name', 'like', "$name%")
            ->get();
    }

    public function oneDataById($id)
    {
        return $this->query_name()
            ->where('t.id', '=', "$id")
            ->get();
    }
    public function sort($name)
    {
        return $this->query_name()
            ->orderBy('t.time')
            ->where('gl.genre_name', $name)
            ->get();
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\TVname;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin/index', ['data' => (new \App\Models\TVname)->data()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/add', ['genres' => (new \App\Models\genre_list())->genres()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $add = new TVname;
        $add->name = $request->input('name');
        $add->time = $request->input('time');
        $add->genre_id = $request->input('genre');
        $add->age_rate = $request->input('age_rate');
        $add->save();
        return redirect()->route('program.index')->with('success', 'Програма додана');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.show', ['data' => (new \App\Models\TVname)->oneDataById($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.edit', [
            'result' => (new \App\Models\TVname)->oneDataById($id),
            'genres' => (new \App\Models\genre_list())->genres()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('TvName')
            ->where('id', $id)
            ->update([
                'name' => $request->input('name'),
                'time' => $request->input('time'),
                'genre_id' => $request->input('genre'),
                'age_rate' => $request->input('age_rate')
            ]);
        return redirect()->route('program.index')->with('success', 'Програма відредагована');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('TVname')->where('id', '=', $id)->delete();
        return redirect()->route('program.index')->with('success', 'Програма видалена');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TVController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TVController extends Controller
{
    public function index()
    {
        return view('guest.home', ['data' => (new \App\Models\TVname)->data(),'genres' => (new \App\Models\Genre_list())->genres()]);
    }
    public function sort($name)
    {
        return view('guest.home', ['data' => (new \App\Models\TVname)->sort($name), 'genres' => (new \App\Models\Genre_list())->genres()]);
    }

    public function find(Request $req)
    {

        $name = $req->name;

        return view('guest.find', ['data' => (new \App\Models\TVname)->oneData($name)]);
    }
}

resources/views/admin/add.blade.php
@extends('admin.layouts.schema')

@section('title',"Admin add")

@section('content')
    <form action="{{route('program.store')}}" method="post">
        @csrf
        <p>
            <label for="name">Назва програми:</label>
            <input type="text" name="name" id="name" required>
        </p>
        <p>
            <label for="time">Час програми:</label>
            <input type="time" name="time" id="time" required>
        </p>
        <p>
            <label for="genre">Жанр:</label>
            <select id="genre" name="genre">
                @foreach($genres as $genre)
                    <option value='{{ $genre->genre_id }}'>{{ $genre->genre_name }}</option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="age">Вікове обмеження:</label>
            <input type="text" id="age" name="age_rate" required>
        </p>
        <button type="submit" class="btn btn-primary">Додати</button>
        <a href="{{route('program.index')}}" class="btn btn-secondary">Назад</a>
    </form>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.layouts.schema')
@foreach($result as $row)

@section('title',$row->name . ' edit')

@section('content')
    <form action="{{route('program.update',['id' => $row->id])}}" method="post">
        <input name="_method" type="hidden" value="PUT">
        @csrf
        <p>
            <label for="name">Назва програми:</label>
            <input type="text" name="name" id="name" value="{{$row->name}}" required>
        </p>
        <p>
            <label for="time">Час програми:</label>
            <input type="time" name="time" id="time" value="{{$row->time}}" required>
        </p>
        <p>
            <label for="genre">Жанр:</label>
            <select id="genre" name="genre">
                @foreach($genres as $genre)
                    <option value='{{ $genre->genre_id }}'>{{ $genre->genre_name }}</option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="age">Вікове обмеження:</label>
            <input type="text" id="age" name="age_rate" value="{{$row->age_rate}}" required>
        </p>
        <button type="submit" class="btn btn-primary">Редагувати</button>
        <a href="{{route('program.index')}}" class="btn btn-secondary">Назад</a>
    </form>
@endsection
@endforeach

resources/views/admin/index.blade.php
@extends('admin.layouts.schema')

@section('title',"Admin main")

resources/views/admin/layouts/header.blade.php
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <p class="h5 my-0 me-md-auto fw-normal">Lapochka production</p>
    <nav class="my-2 my-md-0 me-md-3">
        <a class="p-2 text-dark" href="{{route('program.index')}}">На головну</a>
        <a class="p-2 text-dark" href="{{route('program.create')}}">Додати програму</a>
    </nav>
    <a class="btn btn-outline-primary" href="{{ route('logout') }}"
       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
        {{ __('Logout') }}
    </a>

    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
    </form>
</header>

resources/views/admin/layouts/schema.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>@yield('title')</title>
</head>
<body>
@include('admin.layouts.header')
@yield('content')
@if(isset($data))
    <div class="container">
        @if(\Session::has('success'))
            <div class="alert alert-info">
                {{\Session::get('success')}}
            </div>
        @endif
        <table class="table table-danger table-striped">
            <thead>
            <th>Назва программи</th>
            <th>Час</th>
            <th>Жанр</th>
            <th>Дії</th>
            </thead>
            <tbody>
            @foreach ($data as $row)
                <tr>
                    <td width="300" height="60">
                        {{$row->name}}
                    </td>
                    <td width="300">
                        {{$row->time}}
                    </td>
                    <td width="300">
                        {{$row->genre_name}}
                    </td>
                    <td>
                        <a href="{{route('program.edit',['id' => $row->id]) }}"
                           class="btn btn-outline-success">Редагувати</a>
                        <form action="{{ route('program.destroy' , $row->id)}}" method="POST">
                            <input name="_method" type="hidden" value="DELETE">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-outline-danger">Видалити</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endif
</body>
</html>

resources/views/guest/find.blade.php
@extends('guest.layouts.schema')

@section('title', "Find")

@section('content')
    <div class="d-flex justify-content-center">
    <form action="{{route('find-form')}}" method="post">
        @csrf
        <p>
        <label for="name">Назва програми:</label>
        <input type="text" placeholder="Назва програми" name="name" id="name">
            <p>
        <button type="submit" class="btn btn-primary">Пошук</button>
        <a href="{{route('index')}}" class="btn btn-secondary">Назад</a>
        </p>
    </form>
    </div>
@endsection()

resources/views/guest/home.blade.php
@extends('guest.layouts.schema')

@section('title',"Main")

resources/views/guest/layouts/header.blade.php
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <p class="h5 my-0 me-md-auto fw-normal">Lapochka production</p>
    <nav class="my-2 my-md-0 me-md-3">
        <a class="p-2 text-dark" href="{{route('index')}}">На головну</a>
        <a class="p-2 text-dark" href="{{route('find')}}">Пошук програми</a>
    </nav>
    <a class="btn btn-outline-primary" href="{{route('login')}}">Sign up</a>
</header>

resources/views/guest/layouts/schema.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>@yield('title')</title>
</head>
<body>
@include('guest.layouts.header')
@yield('content')
@if(isset($genres))
    @foreach($genres as $genre)
        <a href="{{route('sort', ['name'=>$genre->genre_name])}}">{{$genre->genre_name}}</a>
    @endforeach
@endif
@if(isset($data))
<div class="container">
    <table class="table table-danger table-striped">
        <thead>
        <th>Назва программи</th>
        <th>Час</th>
        <th>Жанр</th>
        <th>Вікове обмеження</th>
        </thead>
        <tbody>
        @foreach ($data as $row)
        <tr>
            <td width="300" height="60">
                {{$row->name}}
            </td>
            <td width="300">
                {{$row->time}}
            </td>
            <td width="300">
                {{$row->genre_name}}
            </td>
            <td width="300">
                {{$row->age_rate}}
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
    @endif
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Login') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                   Lapochka production
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>